version: '3'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "MyComplexPassword1!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db